import type { GrammarTopic } from '../types';
import topicsJson from '../../content/grammar/topics.json';

// Grammar explainers are local JSON, generated by content/authoring/grammar.py.
const topics: GrammarTopic[] = topicsJson as GrammarTopic[];
const bySlug = new Map(topics.map((t) => [t.slug, t]));

export function getGrammarTopics(): GrammarTopic[] {
  return topics;
}

export function getGrammarTopic(slug: string): GrammarTopic | undefined {
  return bySlug.get(slug);
}
